language: go

go:
    - 1.8.x
env:
    - GOARCH=amd64
sudo: false

script: 
    - go test ./creational/singleton
    - go test ./creational/builder
    - go test ./creational/factory
notifications:
    email: alanrong@gmail.com
